name: Build and Test

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        with:
          fetch-depth: 0
        uses: actions/checkout@v3
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'
      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.10.2
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          include-prerelease: true
          source-url: https://nuget.pkg.github.com/juriekruger/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Build And test
        run: |
         dotnet restore src/BigPurpleBank.Api.Product.sln
         dotnet build --configuration Release src/BigPurpleBank.Api.Product.sln
         dotnet test src/BigPurpleBank.Api.Product.Common.Tests/BigPurpleBank.Api.Product.Common.Tests.csproj

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.GITVERSION_SEMVER }}
          release_name: ${{ env.GITVERSION_SEMVER }}
          draft: false
          prerelease: false
