using System.Net;
using BigPurpleBank.Api.Product.Common.Model;

namespace BigPurpleBank.Api.Product.Common.Exceptions;

/// <summary>
/// Exception generated by model validation
/// </summary>
public class BadRequestException : ApiProductException
{
    public BadRequestException(
        IEnumerable<Error> errors)
    {
        ArgumentNullException.ThrowIfNull(errors);
        Errors = errors.ToList();
    }

    public override HttpStatusCode HttpStatusCode => HttpStatusCode.BadRequest;
}